### ISSUE TITLE
Fix release tar path

### ISSUE THREAD

**Issue by mitjok** [cogini/mix_deploy#1]
The path of the release tar file has changed. More info:
https://github.com/elixir-lang/elixir/commit/9f9f56732fe327284afc34c914f5852e13c7059f#diff-53c844525c23fd1a21c03113baf7e781

**Comment by mitjok** [comment]
@reachfh 
Unpacking fails on ubuntu 16.04 due to  space at the end of the string `TAR_FILE="_build/${MIX_ENV}/${RELEASE_NAME}-${RELEASE_VSN}.tar.gz "`

https://github.com/cogini/mix_deploy/pull/2/commits/42412d219a112a66f22ddf984a7553a62f3b68a0#diff-b3b763648fe0155bc2789aae2c5e3d59L23

**Comment by reachfh** [comment]
Thanks!
