### ISSUE TITLE
Which files should be in version control?

### ISSUE THREAD

**Issue by jeroenhouben** [cogini/mix_deploy#13]
Hi,

Nice documentation 👍 

I would like to know you advise on what to put under version control. There are quite soms config files that get generated. Am I right in thinking that only the changes in `config.exs` should be under version control? Or also the stiff generated by?

```
# Initialize mix_systemd templates
mix systemd.init

# Initialize mix_deploy templates
mix deploy.init
```

basically my question is should I run the above on my dev machine and alter/checkin the results? Or do that only on the build and/or prod servers?

**Comment by reachfh** [comment]
It depends on whether you need to make any changes. 

Generally speaking, I don't check in the templates or generated files. I put this in `.gitignore`

```
/rel/templates/systemd/*
/rel/templates/deploy/*
/bin/deploy-*```

If you do need to do something special, then you can make changes to the templates, then check them into source. 
Or you can make your own template.
