### ISSUE TITLE
Chicken and egg situation with directory creation in systemd 235+

### ISSUE THREAD

**Issue by lackac** [cogini/mix_deploy#8]
In addition to #7, there is another issue with creating directories. For systemd 235+ the task moves the responsibility of creating certain directories over to systemd. This presents an issue though when setting up a new server.

I'm using CodeDeploy to setup the server. Following the guides in your READMEs the systemd service is enabled in `AfterInstall`. My problem is that some scripts before that relies on the directories being present. In particular I have a `deploy-sync-config-ssm` script that's run as the last step of `BeforeInstall` that would create the `/etc/app/environment` file based on values fetched from SSM.

My current workaround is to set `:systemd_version` to `234` so that I'm not relying on those features. Is there a better way to do this? Would it make sense to add an option to force creation of the affected directories even with systemd 235+?

**Comment by reachfh** [comment]
If you run `deploy-sync-config-ssm` as an `exec_start_pre` script, I think it should run after systemd has created the `/etc/app` directory. CodeDeploy is one of the primary ways that I do deploys. The config in https://github.com/cogini/mix-deploy-example/blob/master/config/aws.exs runs `deploy-sync-config-s3` that way. 

There is definitely a timing question. The main use case, I think, is to bootstrap the config using information in the build environment (e.g. specifying a config S3 bucket), then use it to pull config in the runtime environment. When I wrote it, I was thinking that it would be possible to create `/etc/app` and put a file there, but I think it may be better handled by the new "overlays" functionality in the latest mix deploy: https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-overlays
Another issue is that `configuration_dir` is not owned by the app user, so the `exec_start_pre` has to run with elevated permissions (`!`).

I am `jakemorrison` in the Elixir Slack, if you want to chat.

**Comment by reachfh** [comment]
This is a complete running example which builds an Elixir app using CodeBuild and deploys using CodeDeploy: https://github.com/cogini/multi-env-deploy

**Comment by lackac** [comment]
Thanks for the tips, @reachfh. I had considered `exec_start_pre`, but didn't like the idea of slowing down the starting/restarting of the application by fetching the new environment variables. The values don't change that often in our case to warrant spending that extra time there. In any case, I'll do some tests and perhaps I'll reconsider.
